name: promote Dev to ITG
on:
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  promote-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync and Merge Dev into ITG
        run: |
          git config --global user.name"bobbygundala"
          git config --global user.email"bobby.gundala@hp.com"
          git fetch origin
          git checkout ITG
          git merge origin/dev --no-ff -m "Automated merge from dev to ITG"
          git push origin ITG
