name: promote Dev to ITG
on:
  workflow_dispatch:

jobs:
  promote-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync and Merge Dev into ITG
        run: |
          git config --global user.name"Automation-Bot"
          git config --global user.email"actions@github.com"
          git fetch origin dev
          git fetch origin ITG
          git checkout ITG || git checkout -b ITG origin/ITG
          git merge origin/dev --no-ff --strategy-option theirs -m "Automated merge from dev to ITG"
          git push origin ITG
