name: promote Dev to ITG
on:
  workflow_dispatch:

jobs:
  promote-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Merge Dev into ITG
        run: |
          git config --global user.name"Automation-Bot"
          git config --global user.email"actions@github.com"
          git fetch origin ITG
          git checkout ITG
          git merge origin/dev --no-ff -m "Automated merge from dev to ITG"
          git push origin ITG
